### PR TITLE
add new text object up-list

### PR DESCRIPTION
**Pull request by s-kostyaev**
see #17

### CODE REVIEW

**Comment by s-kostyaev** [comment]
@paldepind Is it possible to see coverage on my local machine for test how it increase or decrease?

**Comment by paldepind** [comment]
@s-kostyaev 

No. I don't think there is unfortunately.

I like this PR :+1: Do you want to add more tests for coverage or should I merge as is?

**Comment by s-kostyaev** [comment]
I think that you can merge it now and I can add some tests later after some more usage this feature.

**Comment by paldepind** [comment]
@s-kostyaev You've got it :smile:

**Comment by s-kostyaev** [comment]
Thanks.

**Pull request merged**
