### PR TITLE
add whole buffer object binding

### PR DESCRIPTION
**Pull request by d12frosted**
Just as title says, now there is `B` binding to operate on whole buffer. In case I missed something, just let me know.

### CODE REVIEW

**Comment by paldepind** [comment]
Really great :+1:  I've been thinking about this myself.

I'm not sure about the binding though. <kbd>B</kbd> requires a modifier, and there are still many keys available that does not. I can see that it has mnemonic value. But I'm thinking that using something that is easier to press might be better. For instance <kbd>u</kbd> for b**u**ffer. What do you think?

**Comment by d12frosted** [comment]
Ya, was thinking about the same. Already using `B` and doesn't quite like it. But I do like `u` for that. Pretty mnemonic. Would you like me to update key binding or will you do it?

**Comment by paldepind** [comment]
Please update it and then I'll merge it in :smile: 

This is also consistent with <kbd>y</kbd> for s**y**mbol.

**Comment by d12frosted** [comment]
> Please update it and then I'll merge it in :smile:

Done.

> This is also consistent with y for symbol.

Indeed.

**Comment by paldepind** [comment]
Splendid. Thank you for this contribution.

**Comment by d12frosted** [comment]
You're welcome :)

Thank you for this package :)

~ d12frosted

On Wed, May 4, 2016 at 8:14 PM, Simon Friis Vindum <notifications@github.com

**Pull request merged**
