### PR TITLE
Some minor fixed 

### PR DESCRIPTION
**Pull request by Ergus**
- Fixed issue when `mark-even-if-inactive` is `nil`.
- Forced kbd macro evaluation to fix C-g that was not working.

### CODE REVIEW

**Comment by Ergus** [comment]
Hi, I am trying this and the changes are really minor issues, So I don't understand why some test fail. Maybe the C-g change in the test needs a similar change than in the code? Because C-g was not working before.

in Travis it says for the failing test:
```
  Scenario: Cancel with C-g
    When I insert "first second third"
    And I place the cursor before "second"
    And I press "C-w"
    And I press "C-g"   <- Failed here
    And I press "a"
    Then I should see "first asecond third"
```
But manually this scenario works for me.  Please could you give a look and accept when fixed?

**Comment by Ergus** [comment]
@paldepind 
Hi I just added a simple fancy functionality to change the modeline background color and I tested everything and it seems to work in my system. So the failing test I am pretty sure is a test error, because without my changes the command is bind to `C - g` instead of `C-g`. Could you please give a look and merge my changes or suggest corrections?
Best regards, and thanks in advance.

**Comment by paldepind** [comment]
He @Ergus. Thank you for the PR. I have exams at the moment but I'll take a look as soon as I get the time.

**Comment by Ergus** [comment]
Hi I added some more changes to fix the issue #22 (because I faced it). 

It seems to be working, in spite of Travis shows errors in the tests, but when I try the actions manually they produce the expected output. Could you please check this when you have some time?

**Comment by Ergus** [comment]
Hi:

I just added a new commit to solve #20 with `which-key` integration. I actually wrote to the `which-key` developer to add an API to do this [See](https://github.com/justbur/emacs-which-key/issues/215) 

I also modified the Readme to inform about the changes.

Could you please give a look and accept of fix the changes to be integrated?

**Comment by paldepind** [comment]
Looks super great @Ergus. Thanks a lot. The fixes are nice and the which-key integration is really useful.

Thank again :+1:

**Pull request merged**
