### PR TITLE
add quoted strings support to mark-up-list

### PR DESCRIPTION
**Pull request by s-kostyaev**
See added tests

### CODE REVIEW

**Comment by s-kostyaev** [comment]
Also, does "I should see" step work correct? This step does not fail even when it must.

**Comment by s-kostyaev** [comment]
@paldepind for now I can't reproduce errors that exists on travis. I will try to install old emacs version into some container, docker maybe.

**Comment by s-kostyaev** [comment]
Finally done. @paldepind maybe squash all this commits into one?

**Comment by s-kostyaev** [comment]
@paldepind any reaction?

**Comment by paldepind** [comment]
I apologize for the delay. This looks good so I'm merging 👍 

Thank you for the contribution 😄

**Comment by s-kostyaev** [comment]
Thanks for merging :smiley:

**Pull request merged**
